# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"


config.vm.define "firstVM" do |firstVM|
end

config.vm.define "secondVM" do |secondVM|
end
end



