# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  

	config.vm.define "firstVM" do |firstVM|
	  config.vm.hostname = "firstVM"
 	  config.vm.define "firstVM"
  	  config.vm.network :public_network, :bridge => "wlp3s0: Ethernet"
	  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true		
end

	config.vm.define "secondVM" do |secondVM|
	  config.vm.hostname = "secondVM"
	  config.vm.define "secondVM"
	  config.vm.network :public_network, :bridge => "wlp3s0: Ethernet"
	end
end



